spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.173.115:3306/Fun
    username: root
    password: root
  mybatis:
  type-aliases-package: com.mm.fun.bean
  
  
 
  


  
 

  