spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Fun
    username: root
    password: 123456
  mybatis:
  type-aliases-package: com.mm.fun.bean
  
  
 
  


  
 

  